### ISSUE TITLE
problem about torchvision

### ISSUE THREAD

**Issue by GumpCode** [BoyuanJiang/context_encoder_pytorch#1]
hi, 
I was install torchvision from pip, and it worked.
but when I install torchvision from source, it occured a problem as:
```
Traceback (most recent call last):
  File "test.py", line 79, in <module>
    real_cpu, _ = dataiter.next()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 212, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 239, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 41, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "build/bdist.linux-x86_64/egg/torchvision/datasets/folder.py", line 116, in __getitem__
    img = self.loader(path)
  File "build/bdist.linux-x86_64/egg/torchvision/datasets/folder.py", line 63, in default_loader
    return pil_loader(path)
  File "build/bdist.linux-x86_64/egg/torchvision/datasets/folder.py", line 45, in pil_loader
    with Image.open(f) as img:
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 528, in __getattr__
    raise AttributeError(name)
AttributeError: __exit__
```

It is there anything wrong?
Thanks

**Comment by BoyuanJiang** [comment]
HI,I have just reinstall my torchvision from source and all is ok.From your  Traceback above,it seems that there is something wrong in PIL/Image.py (from last Traceback),so can you use pip list to see your **Pillow**  library's version?In my computer it is **Pillow (4.1.1)**.If your version is too old,you may upgrade it.Feel free to contact me if still have errors.

**Comment by BoyuanJiang** [comment]
@GumpCode HI,I have just reinstall my torchvision from source and all is ok.From your Traceback above,it seems that there is something wrong in PIL/Image.py (from last Traceback),so can you use pip list to see your Pillow library's version?In my computer it is Pillow (4.1.1).If your version is too old,you may upgrade it.Feel free to contact me if still have errors

**Comment by GumpCode** [comment]
@BoyuanJiang hi, I have upgraded my Pillow to 4.1.1, it works, thank you!

**Comment by BoyuanJiang** [comment]
@GumpCode Ok~
