### ISSUE TITLE
运行中出现的错误serWarning: The use of the transforms.

### ISSUE THREAD

**Issue by lzzlxxlsz** [BoyuanJiang/context_encoder_pytorch#14]
你好，按照您的方法，运行test.py.我用的是CPU，在哪个ngpu那里设置为0，但是一运行的话就会出现下边的错误，您知道该怎么解决吗
D:\Anaconda\lib\site-packages\torchvision\transforms\transforms.py:207: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  warnings.warn("The use of the transforms.Scale transform is deprecated, " +
D:\Anaconda\lib\site-packages\torchvision\transforms\transforms.py:207: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  warnings.warn("The use of the transforms.Scale transform is deprecated, " +
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Anaconda\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\Anaconda\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "D:\Anaconda\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\Anaconda\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "D:\Anaconda\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "D:\Anaconda\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "D:\Anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\LZZ\Downloads\context_encoder_pytorch-master\test.py", line 78, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    dataiter = iter(dataloader)
  File "D:\Anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __iter__
  File "D:\Anaconda\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\Anaconda\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "D:\Anaconda\lib\multiprocessing\spawn.py", line 225, in prepare
    return _DataLoaderIter(self)
  File "D:\Anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 560, in __init__
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\Anaconda\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "D:\Anaconda\lib\runpy.py", line 263, in run_path
    w.start()
  File "D:\Anaconda\lib\multiprocessing\process.py", line 112, in start
    pkg_name=pkg_name, script_name=fname)
  File "D:\Anaconda\lib\runpy.py", line 96, in _run_module_code
    self._popen = self._Popen(self)
  File "D:\Anaconda\lib\multiprocessing\context.py", line 223, in _Popen
    mod_name, mod_spec, pkg_name, script_name)
  File "D:\Anaconda\lib\runpy.py", line 85, in _run_code
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Anaconda\lib\multiprocessing\context.py", line 322, in _Popen
    exec(code, run_globals)
  File "C:\Users\LZZ\Downloads\context_encoder_pytorch-master\test.py", line 78, in <module>
    return Popen(process_obj)
  File "D:\Anaconda\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    dataiter = iter(dataloader)
  File "D:\Anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __iter__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "D:\Anaconda\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "D:\Anaconda\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
        is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
return _DataLoaderIter(self)
  File "D:\Anaconda\lib\site-packages\torch\utils\data\dataloader.py", line 560, in __init__
    w.start()
  File "D:\Anaconda\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "D:\Anaconda\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Anaconda\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\Anaconda\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "D:\Anaconda\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "D:\Anaconda\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by noambialik** [comment]
Hi, Don't know if still relevant, but I replaced all `transforms.Scale` at `train.py` with `transforms.Resize`, and moved all code in `train.py` to a `if __name__ == '__main__':` block, and resoved this 2 issues
